jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8090
   servlet:
      context-path: /wanna
      session:
         timeout: 21600s
springdoc:
   swagger-ui:
      path: /swagger-ui.html
spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://localhost:3306/adnwanna
      username: root
      password: 12345
      hikari:
         poolName: pool
